### ISSUE TITLE
Static DB plugin libraries built by default.

### ISSUE THREAD

**Issue by eeriegeek** [NWNX/nwnx2-linux#11]
The makefile for the odmbc plugin attempts to build versions of the MySQL and SQLite plugins which link to the static database libraries (in addition to the dynamic linkage). Some linux releases, specifically RedHat/FedoraCore/CentOS, [remove static libraries](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#Packaging_Static_Libraries) even from devel packages, so in order to build with static linkage you would first have to build the MySQL or SQLite client library yourself. Since most people don't build their own db client libs, the odmbc plugin build will fail on these platforms. This is a suggestion that the static builds be commented out in the default makefile with a note on building the static version if it is needed.

**Comment by niv** [comment]
Long, long resolved ..
