### ISSUE TITLE
It's a mess to install in CentOS 7

### ISSUE THREAD

**Issue by piperun** [NWNX/nwnx2-linux#112]
It complains about:

```
-- Could NOT find Ruby (missing:  RUBY_EXECUTABLE RUBY_INCLUDE_DIR RUBY_LIBRARY) (Required is at least version "1.8")
CMake Warning at plugins/ruby/CMakeLists.txt:11 (message):
  Cannot find ruby libraries.

```

And on x86_64 there is no i686 binaries for Ruby.

Also it can't compile the libraries:

```
make[2]: *** No rule to make target `/usr/lib/liblua.so', needed by `compiled/nwnx_lua.so'.  Stop.
make[2]: Leaving directory `/home/nwn/nwnx2-linux'
make[1]: *** [plugins/lua/CMakeFiles/lua.dir/all] Error 2
make[1]: Leaving directory `/home/nwn/nwnx2-linux'
make: *** [all] Error 2
```

Even though I have lua-devel.i686 installed

Solved: Needed lua.i686.

**Comment by virusman** [comment]
I've just tried compiling on CentOS 7 i386, and it worked.
Multiarch/cross-compiling isn't officially supported, and it really depends on distro support, so I suggest compiling on i386 system.

**Comment by piperun** [comment]
Yeah that's true I forgot to add that it was x64.

I also get this error:
`NWNX Lua Initialized
ERROR: LUA: OnCreate() failed.`

when trying to use nwnstartup.sh
