### ISSUE TITLE
Error when I try to compile on Ubuntu:Xenial

### ISSUE THREAD

**Issue by Ephasme** [NWNX/nwnx2-linux#113]
I followed the steps and when I launch "make" I get this error:

`Scanning dependencies of target always_rebuild_compiled
[  0%] Built target always_rebuild_compiled
Scanning dependencies of target nwnx2
[  1%] Building CXX object CMakeFiles/nwnx2.dir/nwnx2lib.cpp.o
[  1%] Building CXX object CMakeFiles/nwnx2.dir/NWNXBase.cpp.o
[  1%] Building C object CMakeFiles/nwnx2.dir/modules.c.o
[  1%] Building C object CMakeFiles/nwnx2.dir/lists.c.o
[  1%] Building CXX object CMakeFiles/nwnx2.dir/gline.cpp.o
/home/nwn/nwnx2-linux/gline.cpp: In member function ‘int gline::parse(const char*)’:
/home/nwn/nwnx2-linux/gline.cpp:40:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if ((j = line.find('#')) != line.npos)
                                  ^
/home/nwn/nwnx2-linux/gline.cpp:59:56: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     if ((pos = line.find_last_of(']')) != line.npos) {
                                                        ^
/home/nwn/nwnx2-linux/gline.cpp:69:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     if ((pos = line.find('=')) != line.npos) {
                                                ^
[  2%] Building C object CMakeFiles/nwnx2.dir/lib/nwn_data.c.o
[  2%] Building C object CMakeFiles/nwnx2.dir/lib/nwn_funcs.c.o
[  2%] Building C object CMakeFiles/nwnx2.dir/lib/nwn_hooks.c.o
[  2%] Building C object CMakeFiles/nwnx2.dir/lib/nx_hook.c.o
[  2%] Building C object CMakeFiles/nwnx2.dir/lib/nx_log.c.o
[  3%] Building C object CMakeFiles/nwnx2.dir/lib/nx_safe.c.o
[  3%] Building C object CMakeFiles/nwnx2.dir/lib/nx_signature.c.o
/home/nwn/nwnx2-linux/lib/nx_signature.c: In function ‘nx_sig_search_match’:
/home/nwn/nwnx2-linux/lib/nx_signature.c:35:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (((match >> 8) & 0xFF) && p == ((match >> 8) & 0xFF))
                                        ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:38:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (((match >> 16) & 0xFF) && p == ((match >> 16) & 0xFF))
                                         ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:42:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     return (p == (match & 0xFF));
               ^
/home/nwn/nwnx2-linux/lib/nx_signature.c: In function ‘nx_sig_search_destroy_nodes’:
/home/nwn/nwnx2-linux/lib/nx_signature.c:69:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < count; i++) {
                   ^
/home/nwn/nwnx2-linux/lib/nx_signature.c: In function ‘nx_sig_search_add_signature’:
/home/nwn/nwnx2-linux/lib/nx_signature.c:128:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (j = 0; j < state->nxss_count; j++) {
                           ^
/home/nwn/nwnx2-linux/lib/nx_signature.c: In function ‘nx_sig_search_run’:
/home/nwn/nwnx2-linux/lib/nx_signature.c:180:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 0; i < cursors; i++) {
                       ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:184:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (j = 0; j < cur[i]->nxsc_state->nxss_count; j++) {
                           ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:194:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         for (k = 1; k < cursors; k++) {
                                       ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:199:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                         if (k == cursors) {
                               ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:215:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (i = 1; i < cursors; i++) {
                       ^
/home/nwn/nwnx2-linux/lib/nx_signature.c:223:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < cursors; i++) {
                   ^
[  3%] Building CXX object CMakeFiles/nwnx2.dir/lib/NwnDefines.cpp.o
[  3%] Building ASM object CMakeFiles/nwnx2.dir/api/nwnsyms.S.o
/home/nwn/nwnx2-linux/api/nwnsyms.S: Messages de l'assembleur:
/home/nwn/nwnx2-linux/api/nwnsyms.S:1: Erreur: expression absolue erronée ou irréductible
/home/nwn/nwnx2-linux/api/nwnsyms.S:1: Erreur: chaîne manquante
CMakeFiles/nwnx2.dir/build.make:374 : la recette pour la cible « CMakeFiles/nwnx2.dir/api/nwnsyms.S.o » a échouée
make[2]: *** [CMakeFiles/nwnx2.dir/api/nwnsyms.S.o] Erreur 1
CMakeFiles/Makefile2:104 : la recette pour la cible « CMakeFiles/nwnx2.dir/all » a échouée
make[1]: *** [CMakeFiles/nwnx2.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
`

**Comment by virusman** [comment]
Is this a 64-bit or 32-bit Ubuntu 16.04 system?

**Comment by Ephasme** [comment]
Result of uname -a
`Linux fastfrench 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:00:59 UTC 2016 i686 i686 i686 GNU/Linux`

**Comment by Ephasme** [comment]
One more thing, I changed the jvm dependency from java-7 to java-8 otherwise I can't install the whole dependencies.

**Comment by virusman** [comment]
Should be fixed now.
