### ISSUE TITLE
When I try to follow the exact procedure of the README.md I run in a CMAKE error (missing library)

### ISSUE THREAD

**Issue by Ephasme** [NWNX/nwnx2-linux#114]
Steps to reproduce:
- Starts a VM with ubuntu:xenial
- Upgrade VM to latest version
- Clone repository and `cd` into it
- Run `cat apt-dep | xargs sudo apt-get install -y`
- Run `mkdir build && cd build`
- Run `cmake ..`

You should run into this error:

`Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)`

![Error](http://i.imgur.com/7iG11QZ.png)

The missing library is ZLIB, I think it's missing in the dependency file.

**Comment by Ephasme** [comment]
This problem can be fixed by running `sudo apt-get install zlib1g-dev`

**Comment by virusman** [comment]
The preferred way is to run ./compile.sh but it had a typo in zlib1g-dev package name. I'll fix that now.
