### ISSUE TITLE
about zlib not found

### ISSUE THREAD

**Issue by zeerd** [NWNX/nwnx2-linux#115]
I meet this issue below :
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.8")

And the follow command make sense. Maybe you could update the readme.md.
    sudo apt-get install zlib1g-dev:i386

**Comment by jakkn** [comment]
Hello @zeerd, thank you for opening an issue. I will look into it.
It has been a while since I last worked on this and the Dockerfile needs an update. I'll see what I can do.

**Comment by virusman** [comment]
Updated readme & compile script to mention zlib1g-dev.
