### ISSUE TITLE
Raspberry PI 3 - cross-compile

### ISSUE THREAD

**Issue by Paurin1** [NWNX/nwnx2-linux#116]
Hi, 
I'm aware of an Issue #79 but still I don't lose my hope. 
Now, when new Raspberry PI 3 is out, I think it may be a good time to consider a cross-compile from x86 application code to ARM that RPI3 has. 
Has anyone tried it already? Or maybe someone tried to emulate it? If so, then is it worth it?
It's just... sometimes it does not calculate to host a 24h 10player server on a 60-70W computer.

**Comment by niv** [comment]
NWN1 isn't available as a native arm build, so no joy there, and x86 emulation (i.e. through qemu) is way too slow to warrant the effort.

**Comment by Paurin1** [comment]
But do I need an NWN 1 installation to run NWNX2 server?

**Comment by niv** [comment]
Yes. nwnx is a addon to nwn, not a replacement. It needs the original binary to run and that binary is not available for arm architectures.
