### ISSUE TITLE
Adding ability to compile from x86_64 host without ia32 chroot

### ISSUE THREAD

**Issue by rnjacobs** [NWNX/nwnx2-linux#69]
Add
`set(CMAKE_ASM_FLAGS "-mtune=i386 -m32 -mno-accumulate-outgoing-args -Wall -Wno-unused -Wno-write-strings")`
to the CMakeLists.txt

On debian/ubuntu, apt-get Install lib32stdc++-5-dev:amd64, zlib1g-dev:i386, and then optionally the :i386 versions of everything in plugins/*/apt-dep

**Comment by niv** [comment]
That's a good idea. We should rewrite all apt-dep entries to have the :i386 suffix by default as well, so that works on x64 hosts too.

**Comment by rnjacobs** [comment]
Not the ones in the root directory. cmake, build-essential, and gperf can't exist with the amd64 and i386 packages installed side-by-side, and probably should be the native version anyway.

There's a few other plugins that can't, either. Such as ruby2.1:i386 conflicts with ruby2.1:amd64, and libboost-dev:i386 conflicts with all sorts of native compiler things, so maybe vaultster can't be built this way.

 ... I'd do more, but I'm having the worst time getting cmake to explain why it can't find libraries, like sqlite, when they're definitely installed.

**Comment by virusman** [comment]
The current version cross-compiles on a 64-bit system. .travis.yml lists the packages required for that
